Repository Team-Tatorr/Django-Tatorr, pull requests merged in 2020-07, with the labels that each got.

#1 Fix names for new repo
  Django-Tatorr/asgi.py
  Django-Tatorr/settings.py
  Django-Tatorr/urls.py
  Django-Tatorr/wsgi.py
  manage.py
Labels: bug

#2 Jon/dev
  Django-Tatorr/settings.py
  Procfile
Labels: enhancement

#5 Jon/dev
  Django-Tatorr/settings.py
Labels: security enhancement

#6 Jon/dev
  Django-Tatorr/settings.py
Labels: bug

#12 Created Movie night and Team Tatorr main apps. Setup default homepage…
  Django-Tatorr/settings.py
  Django-Tatorr/urls.py
  movie_night/__init__.py
  movie_night/admin.py
  movie_night/apps.py
  movie_night/migrations/__init__.py
  movie_night/models.py
  movie_night/templates/moviecal.html
  movie_night/tests.py
  movie_night/urls.py
  movie_night/views.py
  team_tator_main/__init__.py
  team_tator_main/admin.py
  team_tator_main/apps.py
  team_tator_main/migrations/__init__.py
  team_tator_main/models.py
  team_tator_main/static/team_tator_main/css/cover.css
  team_tator_main/templates/index.html
  team_tator_main/tests.py
  team_tator_main/urls.py
  team_tator_main/views.py
Labels: enhancement
